"""Generator for the ten pages in public/, plus sitemap.xml and robots.txt.

THIS FILE IS THE SOURCE OF THE PAGE MARKUP. The .html files in public/ are build
output: every run rewrites all of them, so an edit made directly to one is lost
the next time anyone runs `npm run pages`. Edit the page bodies below instead.
(Content — stones, specs, markets — lives in public/assets/js/data.js.)

    npm run pages        # regenerate, restamp the service worker, run the checks

Every internal URL is root-absolute and extensionless (/about, /assets/...):
extensionless because Cloudflare redirects /about.html to /about, root-absolute
because 404.html is served at whatever path was missing, however deep.

SITE_URL is the one line to change if the domain changes. Canonical links,
og:url, the share image and every <loc> in the sitemap derive from it.
"""
import pathlib, datetime, posixpath, re

# ---------------------------------------------------------------------------
# The live domain. No trailing slash.
SITE_URL = 'https://www.swasimgranite.com'
# ---------------------------------------------------------------------------

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = ROOT / 'public'          # the publish directory: everything in it ships

# Social cards need an absolute URL — a relative og:image silently resolves to
# nothing, and WhatsApp, LinkedIn and Slack all render a blank card.
# 1200x630 (1.91:1), the ratio every unfurling platform crops to. Built by
# tools/build-share-card.py; a square catalogue photo used to be cropped to
# ribbons here and carried no branding at all.
SHARE_IMAGE = f'{SITE_URL}/assets/img/share-card.jpg'

# Edit by hand, and only when the policy text itself changes. Deliberately not
# derived from the build date: a stylesheet tweak must not silently re-date a
# legal document, because the date is the reader's only record of what changed.
POLICY_UPDATED = '8 September 2026'

HEAD = '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Generated by tools/pages.py. Edit that file and run `npm run pages`; changes made here are overwritten. -->
  <title>{title}</title>
  <meta name="description" content="{desc}">
  <link rel="canonical" href="{canonical}">
{social}  <link rel="preload" href="/assets/fonts/barlow-400.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="preload" href="/assets/fonts/cormorant-garamond-600.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="/assets/css/site.css">
{preloads}  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <meta name="theme-color" content="#0F4C2E">
{extra}</head>
<body data-page="{key}">
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header" data-site-header></header>

<main id="main">
{body}</main>
{after}
<footer class="site-footer" data-site-footer></footer>
<script type="module" src="/assets/js/pages/{script}.js"></script>
</body>
</html>
'''

CTA = '''
  <section class="band--tight band--rule-top">
    <div class="shell cta">
      <h2 class="display display--block t-green">{head}</h2>
      {action}
    </div>
  </section>
'''

PAGES = {}

PAGES['index'] = dict(
  key='home', script='home',
  title='Swasim Granite — Quarry Owners &amp; Granite Exporters, Hosur',
  desc='Swasim Granite has cut and exported premium Indian granite from Hosur since 2010 — blocks, slabs, tiles and monuments, with selection, cutting, finishing and export packing handled in-house.',
  og_title='Swasim Granite — Excellence Carved in Stone',
  og_desc='Premium granite blocks, slabs, tiles and monuments from Hosur, India. '
          'Every step in-house, from block to container.',
  extra='', after='',
  body='''
  <section class="hero">
    <div class="hero__texture" aria-hidden="true"></div>
    <div class="shell hero__inner">
      <div class="rise hero__text">
        <p class="eyebrow eyebrow--rule">EST. 2010 · HOSUR, INDIA</p>
        <h1 class="display display--hero">Excellence<br>Carved in <em>Stone</em></h1>
        <p class="lede">Crafting stone since 2010. We turn raw granite into premium blocks, slabs,
          tiles and monuments — handling selection, cutting, finishing and export packing in-house
          for clients across India, Vietnam, Singapore, Russia and Europe.</p>
        <p class="lede lede--mobile">Hosur, Tamil Nadu. Block to container, in-house —
          exporting to five markets since 2010.</p>
        <div class="row hero-actions">
          <a class="btn btn--primary" href="/catalogue">Explore the Catalogue</a>
          <a class="btn btn--ghost" href="/what-we-do">What We Do</a>
        </div>
        <div class="badges" data-badges></div>
      </div>
      <div class="carousel rise rise--slow" data-carousel></div>
    </div>
    <div class="hero__stats" data-hero-stats></div>
    <div class="trust"><ul data-trust></ul></div>
  </section>

  <section class="band">
    <div class="shell">
      <div class="section-head">
        <div>
          <p class="eyebrow">The Collection</p>
          <h2 class="display display--section t-green">Premium stones we cut every week.</h2>
        </div>
        <a class="link-arrow" href="/catalogue">View full catalogue →</a>
      </div>
      <div class="rail__head mb-xs">
        <span class="label">Featured lots</span>
        <a class="label label--green" href="/catalogue">See all</a>
      </div>
      <div class="stone-grid" data-featured></div>
    </div>
  </section>

  <section class="band band--green">
    <div class="shell split">
      <div>
        <p class="eyebrow">Why Swasim</p>
        <h2 class="display display--section mb-md">Every step in-house, from block to container.</h2>
        <p class="prose prose--on-dark measure-md mb-xl">We handle selection, cutting, finishing and
          export-ready packing ourselves, so what reaches you is consistent, high-quality stone —
          every time. Under Managing Director Roopesh Kumar, we've grown from a local supplier into
          a name trusted across India and international markets.</p>
        <a class="btn btn--ghost" href="/about">More about the plant</a>
      </div>
      <div class="stats" data-stats></div>
    </div>
  </section>
''' + CTA.format(head='Send volumes, thickness and finish.<br>Quote back within one working day.',
                 action='<a class="btn btn--primary" href="/contact">Get a B2B Quote</a>'))

PAGES['about'] = dict(
  key='about', script='about',
  title='About Us — Swasim Granite',
  desc='Based in Hosur, Tamil Nadu, Swasim Granite has turned raw granite into premium stone products since 2010, serving India, Vietnam, Singapore, Russia and Europe.',
  after='',
  extra='',
  body='''
  <section class="masthead masthead--navy">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">About Swasim</p>
      <h1 class="display display--page">Crafting Stone Since 2010</h1>
      <p>Based in Hosur, India, Swasim Granite has been turning raw granite into premium stone
        products for over a decade — serving clients across India, Vietnam, Singapore, Russia and Europe.</p>
    </div>
  </section>

  <section class="band">
    <div class="shell split split--wide">
      <div>
        <h2 class="display display--section t-green mb-md">From a local supplier to a trusted export name.</h2>
        <div class="prose mb-xl">
          <p>Under the leadership of Managing Director Roopesh Kumar, we've grown from a local supplier
            into a trusted name serving clients across India and international markets including
            Vietnam, Singapore, Russia, and Europe.</p>
          <p>We handle every step in-house — from selecting the right block at the source, to precision
            cutting, finishing, and export-ready packing — so what reaches you is consistent,
            high-quality stone, every time.</p>
        </div>
        <div class="stats" data-stats></div>
      </div>
      <div class="plant-frame">
        <figure class="plant" data-plant></figure>
        <div class="corner-tr corner-tr--sm" aria-hidden="true"></div>
      </div>
    </div>
  </section>

  <section class="band band--white band--rule-top anchor" id="markets">
    <div class="shell">
      <p class="eyebrow">Where Our Stone Goes</p>
      <h2 class="display display--section t-green mb-sm measure-lg">Markets we work with, and what we ship there.</h2>
      <p class="prose mb-lg">Select a highlighted country to see what we supply, since when, and how it ships.</p>
      <div data-worldmap></div>
    </div>
  </section>

  <section class="band band--green">
    <div class="shell">
      <p class="eyebrow">What Drives Us</p>
      <h2 class="display display--section mb-lg measure-hd">The three things we don't compromise on.</h2>
      <div class="hairline hairline--dark values-grid" data-values></div>
    </div>
  </section>

  <section class="band anchor" id="infrastructure">
    <div class="shell">
      <p class="eyebrow">Infrastructure</p>
      <h2 class="display display--section t-green mb-md measure-lg">Every stage, under one roof in Hosur.</h2>
      <p class="prose mb-lg">Our Hosur facility carries a shipment through the full journey — from
        block selection to export logistics — so nothing is outsourced and nothing is left to chance.</p>
      <div class="journey" data-journey></div>
    </div>
  </section>
''' + CTA.format(head='See what we make, block to monument.',
                 action='''<div class="row">
        <a class="btn btn--green" href="/what-we-do">What We Do</a>
        <a class="btn btn--outline" href="/catalogue">Granite Catalogue</a>
      </div>'''))

out = SITE

PAGES['catalogue'] = dict(
  key='catalogue', script='catalogue', extra='',
  title='Catalogue — Swasim Granite',
  desc='The Swasim collection: granite and marble varieties with full technical specifications and finish options, plus monument craftsmanship from our Hosur workshop.',
  after='''
<dialog class="lightbox" data-lightbox aria-label="Monument photograph">
  <div class="lightbox__stage"><img alt=""></div>
  <button class="lightbox__close" type="button" data-close aria-label="Close">&times;</button>
  <button class="lightbox__prev"  type="button" data-prev  aria-label="Previous">&#8249;</button>
  <button class="lightbox__next"  type="button" data-next  aria-label="Next">&#8250;</button>
  <div class="lightbox__count" data-count></div>
</dialog>
''',
  body='''
  <section class="masthead">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">Catalogue</p>
      <h1 class="display display--page">The Swasim Collection</h1>
      <p class="mb-xl">Select a stone to load full technical specifications, finish options and a
        full-slab view. All stones available in 2cm / 3cm gangsaw slabs, cut-to-size and tiles.</p>
      <label class="search" for="stone-search">
        <svg width="15" height="15" viewBox="0 0 16 16" fill="none" stroke="currentColor"
             stroke-width="1.6" aria-hidden="true">
          <circle cx="7" cy="7" r="4.5"></circle><path d="M10.5 10.5 14 14"></path>
        </svg>
        <span class="visually-hidden">Search the collection</span>
        <input id="stone-search" type="search" data-search
               placeholder="Search by stone, colour or origin" autocomplete="off">
      </label>
      <div class="chips catalogue-tabs" role="group" aria-label="Catalogue sections">
        <button class="chip chip--on-dark" type="button" data-tab="granite"   aria-pressed="true">Granite</button>
        <button class="chip chip--on-dark" type="button" data-tab="monuments" aria-pressed="false">Monuments</button>
      </div>
    </div>
  </section>

  <section class="band band--browse" data-panel="granite">
    <div class="shell">
      <div class="chips mb-lg" data-filters></div>
      <div class="catalogue">
        <article class="stone-detail" data-detail data-fading="false"></article>
        <div><div class="thumb-grid" data-thumbs></div></div>
      </div>
    </div>
  </section>

  <section class="band band--browse" data-panel="monuments" hidden>
    <div class="shell">
      <div class="mb-lg">
        <h2 class="display display--block t-green mb-xs">Monument Craftsmanship</h2>
        <p class="prose stack-0">A selection of headstones, memorials and custom carvings from our
          workshop — in black, red, grey and multicolour granite, hand-finished and engraved to order.</p>
      </div>
      <div class="gallery" data-gallery></div>
      <div class="centre gallery-cta">
        <a class="btn btn--green" href="/contact">Discuss a Custom Monument</a>
      </div>
    </div>
  </section>
''')

PAGES['what-we-do'] = dict(
  key='what-we-do', script='what-we-do', extra='', after='',
  title='What We Do — Swasim Granite',
  desc='Granite blocks, slabs, tiles, monuments and customised work — and the eight-step quarry-to-delivery journey we run in-house at Hosur.',
  body='''
  <section class="masthead masthead--saffron">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">What We Do</p>
      <h1 class="display display--page">From raw block to finished product.</h1>
      <p>Swasim Granite delivers premium natural stone for projects of every scale —
        residential, commercial, and monumental.</p>
    </div>
  </section>

  <section class="band">
    <div class="shell">
      <p class="eyebrow">Our Products</p>
      <h2 class="display display--section t-green mb-lg measure-hd">Five ways we put granite to work.</h2>
      <div class="product-grid" data-products></div>
    </div>
  </section>

  <section class="band band--green">
    <div class="shell">
      <p class="eyebrow">From Quarry to Delivery</p>
      <h2 class="display display--section mb-md measure-hd">We don't just supply stone — we manage the entire journey.</h2>
      <p class="prose prose--on-dark measure-md mb-lg">Every block is hand-picked, every slab
        quality-checked, and every shipment packed to survive the journey — whether it's headed
        across the state or across the globe.</p>
      <div class="journey journey--dark" data-journey></div>
    </div>
  </section>
''' + CTA.format(head='Ask for the block photo set before you commit to a lot.',
                 action='<a class="btn btn--primary" href="/contact">Request Lot Photos</a>'))

PAGES['articles'] = dict(
  key='articles', script='articles', extra='', after='',
  title='Articles &amp; Insights — Swasim Granite',
  desc='Practical writing for people who buy, specify and fabricate stone — buyer guides, finishes, export packing and process notes from the Swasim yard and floor.',
  body='''
  <section class="masthead">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">Articles &amp; Insights</p>
      <h1 class="display display--page">Notes from the quarry and the floor.</h1>
      <p>Practical writing for the people who buy, specify and fabricate stone — what we've learned
        running every step in-house since 2010.</p>
    </div>
  </section>

  <section class="band band--feed">
    <div class="shell">
      <div class="chips mb-xl">
        <span class="label">Topic</span>
        <span class="chips" data-filters></span>
      </div>
      <article class="feature" data-feature></article>
      <div class="article-grid" data-articles></div>
    </div>
  </section>

  <section class="band--tight band--green">
    <div class="shell cta">
      <div>
        <h2 class="display display--block mb-xs">Have a question we should write about?</h2>
        <p class="prose prose--on-dark measure-sm stack-0">Send it to the export desk — the questions
          buyers ask most often are the ones that end up here.</p>
      </div>
      <a class="btn btn--primary" href="/contact">Ask The Desk</a>
    </div>
  </section>
''')

PAGES['brochure'] = dict(
  key='brochure', script='brochure', extra='', after='',
  title='Brochure — Swasim Granite',
  desc='Request the Swasim Granite company brochure: full product range, finishes, specifications, the quarry-to-delivery process and export contacts.',
  body='''
  <section class="masthead">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">Company Brochure</p>
      <h1 class="display display--page">Our full range, on paper.</h1>
      <p>Products, finishes and the export process in one document — for architects, fabricators
        and importers evaluating Swasim Granite.</p>
    </div>
  </section>

  <section class="band band--deep">
    <div class="shell split">
      <div class="brochure-cover">
        <img src="/assets/granite/indian-juparana.jpg" alt="" decoding="async">
        <div class="brochure-cover__wash"></div>
        <div class="brochure-cover__text">
          <p class="eyebrow mb-xs">Swasim Granite</p>
          <div class="display display--block">Company<br>Brochure</div>
          <p class="label t-dim">PDF · AVAILABLE ON REQUEST</p>
        </div>
      </div>
      <div>
        <h2 class="display display--section t-green mb-md">What's inside</h2>
        <ul class="tick-list" data-contents></ul>
        <p class="t-muted measure-sm mb-xl">A downloadable PDF will be linked here once ready. In the
          meantime, request a copy and our export desk will send it directly.</p>
        <a class="btn btn--primary" href="/contact">Request the Brochure</a>
      </div>
    </div>
  </section>
''')

PAGES['testimonials'] = dict(
  key='testimonials', script='testimonials', extra='', after='',
  title='Testimonials — Swasim Granite',
  desc='Feedback from the fabricators, importers and contractors Swasim Granite works with across India and abroad.',
  body='''
  <section class="masthead">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">Testimonials</p>
      <h1 class="display display--page">What clients say.</h1>
      <p>Feedback from fabricators, importers and contractors we've worked with across India and abroad.</p>
    </div>
  </section>

  <section class="band band--deep">
    <div class="shell">
      <div class="quote-grid" data-testimonials></div>
    </div>
  </section>

  <section class="band--tight band--green">
    <div class="shell cta">
      <h2 class="display display--block measure-hd">Worked with us? We'd love to feature your feedback here.</h2>
      <a class="btn btn--primary" href="/contact">Send Your Feedback</a>
    </div>
  </section>
''')

PAGES['contact'] = dict(
  key='contact', script='contact', extra='', after='',
  title='Contact Us — Swasim Granite',
  desc='Request a B2B quote for granite blocks, slabs, tiles, monuments or custom work. Swasim Granite, Shoolgiri / Sappadi, Hosur, Tamil Nadu. Quotes within one working day.',
  body='''
  <section class="masthead">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">B2B Inquiry</p>
      <h1 class="display display--page">Have a project in mind,<br>or need a quote?</h1>
      <p>We'd love to hear from you — on granite blocks, slabs, tiles, monuments or custom work.</p>
    </div>
  </section>

  <section class="band band--intro">
    <div class="shell split split--start">
      <div>
        <h2 class="display display--block t-green mb-md">Get in Touch</h2>
        <dl class="contact-lines mb-xl" data-contact-lines></dl>
        <div class="contact-actions" data-contact-actions></div>
        <dl class="hours mb-xl" data-hours></dl>
        <!-- Locator, not an embed. A live Google Maps iframe sets third-party
             cookies the moment it loads, which is the whole reason a site like
             this would otherwise need a consent banner. The address, the
             coordinates and a directions link do the job a buyer actually needs
             without a third-party request, and the map is visible immediately
             rather than waiting on a tap. -->
        <div class="locator">
          <div class="locator__map" aria-hidden="true">
            <span class="locator__pin"></span>
            <span class="locator__ring"></span>
          </div>
          <div class="locator__body">
            <p class="locator__place">Shoolgiri / Sappadi, Hosur</p>
            <p class="locator__region">Tamil Nadu, India</p>
            <p class="locator__coords">12.7409&deg; N, 77.8253&deg; E</p>
            <a class="btn btn--outline locator__go" rel="noopener"
               href="https://www.google.com/maps/search/?api=1&amp;query=Shoolgiri%2C+Hosur%2C+Tamil+Nadu%2C+India">
              Get directions</a>
          </div>
        </div>
      </div>

      <form class="form" data-enquiry novalidate>
        <div class="form__row">
          <label class="field">Full name
            <input type="text" name="name" placeholder="Anita Raghavan" autocomplete="name" required>
          </label>
          <label class="field">Company
            <input type="text" name="company" placeholder="Stoneworks Ltd." autocomplete="organization">
          </label>
        </div>
        <div class="form__row">
          <label class="field">Email
            <input type="email" name="email" placeholder="buyer@company.com" autocomplete="email" required>
          </label>
          <label class="field">Destination port
            <input type="text" name="port" placeholder="Rotterdam">
          </label>
        </div>
        <div class="form__row">
          <label class="field">Stone of interest
            <select name="stone" data-stones></select>
          </label>
          <label class="field">Finish
            <select name="finish" data-finishes></select>
          </label>
        </div>
        <label class="field">Requirement
          <textarea name="requirement" rows="4"
            placeholder="e.g. 2 containers, 3cm polished gangsaw slabs, monthly repeat" required></textarea>
        </label>
        <!-- Spam trap. Hidden from people by CSS and from screen readers by
             aria-hidden; a scripted submitter fills every field it finds, so
             anything arriving with this set is discarded. Costs no third-party
             script, no CAPTCHA and nothing for a real buyer to solve. -->
        <div class="hp" aria-hidden="true">
          <label>Fax number
            <input type="text" name="fax" tabindex="-1" autocomplete="off">
          </label>
        </div>
        <button class="btn btn--primary full" type="submit">Send B2B Inquiry</button>
        <p class="form__note" data-form-note role="status" hidden></p>
      </form>
    </div>
  </section>
''')

PAGES['privacy'] = dict(
  key='privacy', script='privacy',
  title='Privacy Policy — Swasim Granite',
  desc='How Swasim Granite handles the information you send through this website: what the enquiry form collects, how it reaches us, and the fact that this site sets no cookies and runs no analytics.',
  og_title='Privacy Policy — Swasim Granite',
  og_desc='What the enquiry form collects, how it reaches us, and how long we keep it.',
  extra='', after='',
  body='''
  <section class="masthead masthead--navy">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">Legal</p>
      <h1 class="display display--page">Privacy Policy</h1>
      <p>What this website collects, why, and what we do with it. Written to be read,
        not to be scrolled past.</p>
    </div>
  </section>

  <section class="band">
    <div class="shell legal">
      <p class="legal__updated">Last updated ''' + POLICY_UPDATED + '''</p>

      <h2>The short version</h2>
      <p>This website sets <strong>no cookies</strong>, runs <strong>no analytics</strong>, and
        contains <strong>no advertising or tracking pixels</strong>. The only personal information
        it handles is what you choose to type into the enquiry form. We use that to answer your
        enquiry. We do not sell it and we do not share it for marketing.</p>

      <h2>Who we are</h2>
      <p>Swasim Granite, quarry owners, processors and exporters of Indian granite, based at
        Shoolgiri / Sappadi, Hosur, Tamil Nadu, India. For anything in this policy — including a
        request to see, correct or delete your information — contact us at
        <a href="mailto:swasimgranite@gmail.com">swasimgranite@gmail.com</a> or
        <a href="tel:+919448841482">+91 94488 41482</a>.</p>

      <h2>What we collect</h2>
      <p>Only what you enter in the enquiry form on our
        <a href="/contact">contact page</a>:</p>
      <ul>
        <li>your name</li>
        <li>your company (optional)</li>
        <li>your email address</li>
        <li>your destination port (optional)</li>
        <li>the stone and finish you are interested in</li>
        <li>the requirement you describe</li>
      </ul>
      <p>There are no other forms on this site, and no hidden fields that collect anything else.
        Separately, and like every website, our hosting provider keeps standard server logs
        (IP address, time of request, page requested) for security and diagnostics.</p>

      <h2>How it reaches us</h2>
      <p>The enquiry form is delivered to us by email. If you instead use the <em>Call</em>,
        <em>WhatsApp</em> or email links on the site, those open your own phone or email
        application — this website does not see or record anything you send that way, and your
        use of WhatsApp is governed by WhatsApp's own privacy terms, not ours.</p>

      <h2>Cookies and tracking</h2>
      <p>This site sets no cookies of any kind, and there is nothing to consent to. We do not use
        Google Analytics or any equivalent, we do not embed advertising or social tracking
        scripts, and no third party receives information about your visit.</p>

      <h2>What is stored on your device</h2>
      <p>To work smoothly on slow or intermittent connections, this site stores a copy of its own
        pages, images and fonts in your browser's cache. That copy stays on your device, is never
        sent anywhere, identifies nobody, and disappears when you clear your browser's site data.
        It is a speed measure, not a tracking one.</p>

      <h2>Why we use your information, and for how long</h2>
      <p>We use your enquiry to reply to you, prepare a quotation, and — if you go ahead — to
        fulfil and ship your order. We keep it for as long as we are doing business with you, and
        afterwards for the period we are required to retain commercial and tax records under
        Indian law. Enquiries that do not lead to business are deleted once they are clearly no
        longer live.</p>

      <h2>Who else sees it</h2>
      <p>Our hosting and email providers process it on our behalf in order to deliver the site
        and our mail. Nobody else. We do not sell, rent or trade your information, and we do not
        pass it to third parties for their own marketing.</p>

      <h2>Your rights</h2>
      <p>You can ask us what information we hold about you, ask us to correct it, or ask us to
        delete it. Email <a href="mailto:swasimgranite@gmail.com">swasimgranite@gmail.com</a> and
        we will respond. If you are in the European Economic Area or the United Kingdom, the GDPR
        gives you these rights and the right to complain to your national data protection
        authority; if you are in India, the Digital Personal Data Protection Act, 2023 applies.</p>

      <h2>Changes</h2>
      <p>If this policy changes, the revised version will appear on this page with a new date at
        the top.</p>
    </div>
  </section>
''')

PAGES['404'] = dict(
  key='404', script='notfound',
  title='Page Not Found — Swasim Granite',
  desc='That page does not exist. Browse the granite catalogue, see what we do, or contact the Swasim Granite export desk.',
  og_title='Page Not Found — Swasim Granite',
  og_desc='That page does not exist — but the catalogue and the export desk do.',
  extra='', after='',
  body='''
  <section class="masthead masthead--ink notfound">
    <div class="masthead__texture" aria-hidden="true"></div>
    <div class="masthead__inner">
      <p class="eyebrow">Error 404</p>
      <h1 class="display display--page">This page has been quarried out.</h1>
      <p>The link you followed does not lead anywhere on this site — it may be out of date, or
        mistyped. Everything below is still exactly where it should be.</p>
      <div class="row hero-actions notfound__actions">
        <a class="btn btn--primary" href="/catalogue">Browse the Catalogue</a>
        <a class="btn btn--ghost" href="/">Back to Home</a>
      </div>
    </div>
  </section>

  <section class="band">
    <div class="shell">
      <p class="eyebrow">Where you probably meant to go</p>
      <h2 class="display display--section t-green mb-md measure-lg">The pages buyers reach for most.</h2>
      <ul class="notfound__links" data-notfound-links></ul>
    </div>
  </section>
''')

# ---------------------------------------------------------------------------
# Machine-readable identity. Search engines treat a quarry with a real address,
# phone and opening hours very differently from an anonymous brochure site, and
# this is the only way to state those facts unambiguously. Kept on the two pages
# where it is truthful — the homepage (the organisation) and contact (the place).
# ---------------------------------------------------------------------------
ORG_JSONLD = '''  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": "{site}/#organisation",
    "name": "Swasim Granite",
    "url": "{site}/",
    "logo": "{site}/assets/brand/swasim-logo.png",
    "image": "{share}",
    "description": "Quarry owners, processors and exporters of Indian granite \\u2014 blocks, slabs, tiles and monuments.",
    "foundingDate": "2010",
    "email": "swasimgranite@gmail.com",
    "telephone": "+91-94488-41482",
    "address": {{
      "@type": "PostalAddress",
      "streetAddress": "Shoolgiri / Sappadi",
      "addressLocality": "Hosur",
      "addressRegion": "Tamil Nadu",
      "addressCountry": "IN"
    }},
    "areaServed": ["IN", "VN", "SG", "RU", "EU"],
    "knowsAbout": ["Granite blocks", "Granite slabs", "Granite tiles", "Granite monuments"]
  }}
  </script>
'''.format(site=SITE_URL, share=SHARE_IMAGE)

# ---------------------------------------------------------------------------
# Sitemap weighting. Not every page earns equal standing: the catalogue and the
# quote form are what a buyer is looking for, the brochure and articles are not.
# ---------------------------------------------------------------------------
PRIORITY = {
    'index': '1.0', 'catalogue': '0.9', 'contact': '0.9', 'what-we-do': '0.8',
    'about': '0.7', 'testimonials': '0.6', 'brochure': '0.6', 'articles': '0.5',
    'privacy': '0.3',
}
NOINDEX = {'404'}          # a 404 must never be offered to a crawler


def page_url(name):
    """Canonical URL. Extensionless: Cloudflare redirects /about.html to /about,
    so a canonical or sitemap entry ending in .html points crawlers at a redirect."""
    return f'{SITE_URL}/' if name == 'index' else f'{SITE_URL}/{name}'


IMPORT_RE = re.compile(r'''^\s*import\s+(?:[^'"]*?\s+from\s+)?['"](\.{1,2}/[^'"]+)['"]''', re.M)


def module_graph(entry):
    """Every module a page's script imports, directly or transitively, in the
    order the browser would discover them."""
    seen, queue = [], [entry]
    while queue:
        mod = queue.pop(0)
        if mod in seen:
            continue
        seen.append(mod)
        src = (SITE / mod.lstrip('/')).read_text(encoding='utf-8')
        queue += [posixpath.normpath(posixpath.join(posixpath.dirname(mod), rel))
                  for rel in IMPORT_RE.findall(src)]
    return seen


def first_hero_image():
    """The first hero slide is the homepage's largest paint. Read it from the
    content model, so reordering HERO in data.js cannot leave a stale preload."""
    data = (SITE / 'assets/js/data.js').read_text(encoding='utf-8')
    hero = re.search(r"export const HERO = \[\s*\{\s*id:\s*'([^']+)'", data)
    stone = hero and re.search(r"\{ id: '" + re.escape(hero.group(1)) + r"'[^}]*?img: '([^']+)'", data)
    if not stone:
        raise SystemExit('pages.py: could not find the first HERO stone and its img in data.js')
    return re.sub(r'\.(jpe?g|png)$', '.webp', stone.group(1))


def preloads(script, hero_image=None):
    """Discovery hints. Without them the browser learns of each module only after
    running the one that imports it — a three-deep waterfall that held the home
    hero photo back until ~1.7s on a 300ms-latency phone link. With them the
    measured LCP on that link went from 3.8s to 1.8s."""
    tags = []
    if hero_image:
        tags.append(f'<link rel="preload" as="image" href="{hero_image}" type="image/webp" fetchpriority="high">')
    tags += [f'<link rel="modulepreload" href="{m}">' for m in module_graph(f'/assets/js/pages/{script}.js')]
    return ''.join(f'  {t}\n' for t in tags)


def social_block(name, cfg):
    """Build the canonical/OpenGraph/Twitter block for one page.

    Generated rather than hand-written per page: seven of the eight pages
    previously shipped with no og tags at all, so sharing any of them produced
    an empty card.
    """
    url = page_url(name)
    title = cfg.get('og_title') or cfg['title']
    desc = cfg.get('og_desc') or cfg['desc']
    tags = [
        ('og:site_name', 'Swasim Granite'),
        ('og:title', title),
        ('og:description', desc),
        ('og:type', 'website'),
        ('og:url', url),
        ('og:image', SHARE_IMAGE),
        ('og:locale', 'en_IN'),
    ]
    out = ''.join(f'  <meta property="{k}" content="{v}">\n' for k, v in tags)
    out += '  <meta name="twitter:card" content="summary_large_image">\n'
    if name in NOINDEX:
        out += '  <meta name="robots" content="noindex">\n'
    return out


written = []
for name, cfg in PAGES.items():
    url = page_url(name)
    page = dict(cfg)
    page['canonical'] = url
    page['social'] = social_block(name, cfg)
    page['preloads'] = preloads(cfg['script'], first_hero_image() if name == 'index' else None)
    if name in ('index', 'contact'):
        page['extra'] = page.get('extra', '') + ORG_JSONLD
    page.pop('og_title', None)
    page.pop('og_desc', None)
    (out / f'{name}.html').write_text(HEAD.format(**page), encoding='utf-8')
    written.append(name)

# ---------------------------------------------------------------------------
# sitemap.xml and robots.txt — generated here so they can never list a page that
# no longer exists, or miss one that was just added.
# ---------------------------------------------------------------------------
today = datetime.date.today().isoformat()
entries = ''
for n in sorted(written):
    if n in NOINDEX:
        continue
    loc = page_url(n)
    entries += (f'  <url>\n    <loc>{loc}</loc>\n'
                f'    <lastmod>{today}</lastmod>\n'
                f'    <priority>{PRIORITY.get(n, "0.5")}</priority>\n  </url>\n')

(out / 'sitemap.xml').write_text(
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    f'{entries}</urlset>\n', encoding='utf-8')

(out / 'robots.txt').write_text(
    '# Swasim Granite\n'
    'User-agent: *\n'
    'Allow: /\n'
    '\n'
    f'Sitemap: {SITE_URL}/sitemap.xml\n', encoding='utf-8')

indexed = len([n for n in written if n not in NOINDEX])
print(f'generated {len(written)} pages:', ', '.join(sorted(written)))
print(f'         sitemap.xml ({indexed} urls), robots.txt  —  site: {SITE_URL}')
